version: "3.8"

services:
  eureka:
    build: ./java/eureka
    ports:
      - 8761:8761

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password

  database:
    build: ./java/database
    depends_on:
      - eureka
      - postgres
    ports:
      - 8081:8081
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8761/eureka
        -DPOSTGRES_SERVER=jdbc:postgresql://postgres:5432/postgres

  investments:
    build: ./java/investments
    depends_on:
      - eureka
      - database
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8761/eureka
