FROM --platform=linux/amd64 openjdk:17-jdk-alpine
ENV JAVA_OPTS=""
VOLUME /tmp
ADD target/investments.jar app.jar
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]
